;; The first three lines of this file were inserted by DrRacket. They record metadata
;; about the language level of this file in a form that our tools can easily process.
#reader(lib "htdp-intermediate-lambda-reader.ss" "lang")((modname |12|) (read-case-sensitive #t) (teachpacks ()) (htdp-settings #(#t constructor repeating-decimal #f #t none #f ())))
; Project Euler
; Problem 12 Solution
; by Eli Spiro
; January 3, 2010


; The sequence of triangle numbers is generated by adding the natural numbers.
; So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28.
; The first ten terms would be:
; 
; 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
; 
; Let us list the factors of the first seven triangle numbers:
; 
;  1: 1
;  3: 1,3
;  6: 1,2,3,6
; 10: 1,2,5,10
; 15: 1,3,5,15
; 21: 1,3,7,21
; 28: 1,2,4,7,14,28
; We can see that 28 is the first triangle number to have over five divisors.
; 
; What is the value of the first triangle number to have over five hundred divisors?


;; triangle-number: num -> num
;; generates the nth triangle number
(define (triangle-number x)
  (cond[(= 1 x) 1]
       [else (+ x (triangle-number (sub1 x)))]))

;; number-of-divisors: num -> num
;; determines the number of divisors of a given number
(define (number-of-divisors composite)
  (local [(define (number-of-divisors-helper composite divisors current)
            (cond[(> current composite)
                  divisors]
                 [(zero? (remainder composite current))
                  (number-of-divisors-helper composite (add1 divisors) (add1 current))]
                 [else
                  (number-of-divisors-helper composite divisors (add1 current))]))]
    (number-of-divisors-helper composite 0 1)))

;; first-triangle-number-divisors: num -> num
;; finds the first triangle number with at least the given number of divisors
(define (first-triangle-number-divisors divisors)
  (local [(define (first-triangle-number-divisors-helper divisors current)
            (cond[(>= (number-of-divisors (triangle-number current)) divisors)
                  (triangle-number current)]
                 [else (first-triangle-number-divisors-helper divisors (add1 current))]))]
    (first-triangle-number-divisors-helper divisors 1)))

(first-triangle-number-divisors 500)